- hosts: all
  become: yes
  vars:
    db_name: wordpress
    db_user: wordpress
    db_password: secret
    root_password: rootsecret
    wp_version: "6.2"
    db_host: localhost
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install LAMP packages, zip and awscli
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - python3-pip
          - zip
          - awscli

    - name: Install PyMySQL module
      pip:
        name: PyMySQL

    - name: Start Apache service
      service:
        name: apache2
        state: started

    - name: Start MySQL service
      service:
        name: mysql
        state: started

    - name: Create .my.cnf file for root user
      copy:
       dest: "/root/.my.cnf"
       content: |
        [client]
        user=root
        password={{ root_password }}
        host={{ db_host }}
        socket=/var/run/mysqld/mysqld.sock
       mode: '0600'

    - name: "Mysql Configuration - Resetting RootPassword"
      mysql_user:
        login_user: root
        login_password: ''
        name: root
        host_all: yes   
        password: "{{root_password}}"
        login_unix_socket: /var/run/mysqld/mysqld.sock



    - name: Create WordPress database
      mysql_db:
        login_user: root
        login_password: "{{ root_password}}"
        name: "{{ db_name }}"
        state: present

    - name: Create WordPress database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
    - name: Grant PROCESS privilege to WordPress database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "*.*:PROCESS"
        append_privs: yes
        state: present

    - name: Download WordPress
      get_url:
        url: "https://wordpress.org/wordpress-{{ wp_version }}.tar.gz"
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress archive
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Update WordPress wp-config.php file
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php

    - name: Set ownership of WordPress files
      file:
        path: /var/www/html/wordpress/
        owner: www-data
        group: www-data
        recurse: yes

    - name: Set permissions of WordPress files
      file:
        path: /var/www/html/wordpress/
        mode: 0755
        recurse: yes

